// This file was generated by Prisma
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL ||
      'postgresql://safari_admin:safari_dev_password_2026@localhost:5432/safari_booking_dev?schema=public',
  },
});
